import { VirtualConfigType } from "../types/VirtualConfigType";

export const defaultVirtualConfig: VirtualConfigType = {
  model: "",
  animations: {
    face: {
      voice: "/like.mp3",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Idle/Sleepy_yawn_idle_113.vmd",
    },
    chest: {
      voice: "/angry.mp3",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Misc/State/Hand_on_cheast_106.vmd",
    },
    lower: {
      voice: "/shy.mp3",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Idle/Sleepy_yawn_idle_113.vmd",
    },
  },
  parts: {
    face: {
      startX: -0.82,
      endX: 0.82,
      startY: 2.64,
      endY: 0.19,
    },
    chest: {
      startX: -0.82,
      endX: 0.82,
      startY: -0.87,
      endY: -2.54,
    },
    lower: {
      startX: -1.34,
      endX: 1.6,
      startY: -4.13,
      endY: -5.73,
    },
  },
  position: [0, -16, 0],
  preloadMotions: [
    {
      uid: "idle-1",
      sentiment: "idle",
      url: "https://s3.ap-southeast-1.amazonaws.com/waifu-cdn.virtuals.gg/vmds/a_idle_neutral_loop_88.vmd",
    },
    {
      uid: "like",
      sentiment: "idle",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Idle/Sleepy_yawn_idle_113.vmd",
    },
    {
      uid: "angry",
      sentiment: "idle",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Misc/State/Hand_on_cheast_106.vmd",
    },
    {
      uid: "shy",
      sentiment: "idle",
      url: "https://s3.ap-southeast-1.amazonaws.com/cdn-staging.hiddenhands.io/vmd/Idle/Sleepy_yawn_idle_113.vmd",
    },
  ],
  stiffness: 6,
};

// MMD available morphs
// {
//   "真面目": 0,
//   "困る": 1,
//   "にこり": 2,
//   "怒り": 3,
//   "上": 4,
//   "下": 5,
//   "まばたき": 6,
//   "笑い": 7,
//   "笑い1": 8,
//   "ウィンク": 9,
//   "ウィンク右": 10,
//   "ウィンク２": 11,
//   "ｳｨﾝｸ２右": 12,
//   "瞳小": 13,
//   "瞳縦潰れ": 14,
//   "恐ろしい子！": 15,
//   "なごみ": 16,
//   "はちゅ目": 17,
//   "はぅ": 18,
//   "ｷﾘｯ": 19,
//   "ｷﾘｯ1": 20,
//   "ｷﾘｯ2": 21,
//   "ｷﾘｯ3": 22,
//   "ｷﾘｯ4": 23,
//   "ｷﾘｯ5": 24,
//   "びっくり": 25,
//   "びっくり1": 26,
//   "じと目": 27,
//   "じと目1": 28,
//   "あ": 29,
//   "い": 30,
//   "い1": 31,
//   "う": 32,
//   "え": 33,
//   "お": 34,
//   "お1": 35,
//   "あ２": 36,
//   "倒ω": 37,
//   "にやり２": 38,
//   "にやり3": 39,
//   "□": 40,
//   "□1": 41,
//   "□2": 42,
//   "□3": 43,
//   "□4": 44,
//   "□5": 45,
//   "□6": 46,
//   "ワ": 47,
//   "ワ1": 48,
//   "ワ2": 49,
//   "口上": 50,
//   "口下": 51,
//   "口角下げ": 52,
//   "口角下げ1": 53,
//   "口角下げ2": 54,
//   "口角下げ3": 55,
//   "口角下げ4": 56,
//   "口角下げ5": 57,
//   "口角下げ6": 58,
//   "口角下げ7": 59,
//   "口角下げ8": 60,
//   "口角下げ9": 61,
//   "口角上げ": 62,
//   "口横缩げ": 63,
//   "口横広げ": 64,
//   "照れ": 65
// }

export const lipsyncMapping = {
  A: "真面目",
  B: "い",
  C: "え",
  D: "あ",
  E: "お",
  F: "う",
  G: "真面目",
  H: "真面目",
  X: "真面目",
};

export const lipsyncVrmMapping = {
  A: "",
  B: "ih",
  C: "ee",
  D: "aa",
  E: "oh",
  F: "ou",
  G: "",
  H: "",
  X: "",
};
