export const boneMap: { [id: string]: string } = {
  下半身: "hips",
  センター: "hips",
  上半身: "spine",
  上半身2: "chest",
  上半身3: "upperChest",
  首: "neck",
  頭: "head",
  右肩: "rightShoulder",
  右肩P: "rightShoulder",
  右肩C: "rightShoulder",
  右腕: "rightUpperArm",
  右ひじ: "rightLowerArm",
  右手首: "rightHand",
  右親指０: "rightThumbMetacarpal",
  右親指0: "rightThumbMetacarpal",
  右親指１: "rightThumbProximal",
  右親指２: "rightThumbDistal",
  右小指１: "rightLittleProximal",
  右小指２: "rightLittleIntermediate",
  右小指３: "rightLittleDistal",
  右薬指１: "rightRingProximal",
  右薬指２: "rightRingIntermediate",
  右薬指３: "rightRingDistal",
  右中指１: "rightMiddleProximal",
  右中指２: "rightMiddleIntermediate",
  右中指３: "rightMiddleDistal",
  右人指１: "rightIndexProximal",
  右人指２: "rightIndexIntermediate",
  右人指３: "rightIndexDistal",
  左肩: "leftShoulder",
  左腕: "leftUpperArm",
  左ひじ: "leftLowerArm",
  左手首: "leftHand",
  左親指０: "leftThumbMetacarpal",
  左親指0: "leftThumbMetacarpal",
  左親指１: "leftThumbProximal",
  左親指２: "leftThumbDistal",
  左小指１: "leftLittleProximal",
  左小指２: "leftLittleIntermediate",
  左小指３: "leftLittleDistal",
  左薬指１: "leftRingProximal",
  左薬指２: "leftRingIntermediate",
  左薬指３: "leftRingDistal",
  左中指１: "leftMiddleProximal",
  左中指２: "leftMiddleIntermediate",
  左中指３: "leftMiddleDistal",
  左人指１: "leftIndexProximal",
  左人指２: "leftIndexIntermediate",
  左人指３: "leftIndexDistal",
  右目: "rightEye",
  左目: "leftEye",
  右足: "rightUpperLeg",
  右ひざ: "rightLowerLeg",
  右足首: "rightFoot",
  右足先EX: "rightToes",
  右つま先: "rightToes", // self added
  左足: "leftUpperLeg",
  左ひざ: "leftLowerLeg",
  左足首: "leftFoot",
  左足先EX: "leftToes",
};

// export const boneMap = {
//   全ての親: undefined,
//   secondary: undefined,
//   Jacket: undefined,
//   Cloth: undefined,
//   Body: undefined,
//   Armature: undefined,
//   センター: undefined,
//   下半身: "hips",
//   腰: "spine",
//   右足: "rightFoot",
//   右ひざ: "rightLowerLeg",
//   右足首: "", // right ankle
//   右つま先: "rightToes",
//   "Toes.R_end": "rightToes",
//   左足: "leftFoot",
//   左ひざ: "",
//   左足首: "",
//   左つま先: "",
//   "Toes.L_end": "",
//   上半身: "",
//   上半身2: "",
//   "Chest Collider": "",
//   右肩: "",
//   右腕: "",
//   右ひじ: "",
//   右手首: "",
//   右親指０: "",
//   右親指１: "",
//   右親指２: "",
//   "Distal Thumb.R_end": "",
//   右薬指１: "",
//   右薬指２: "",
//   右薬指３: "",
//   "Distal Ring.R_end": "",
//   右中指１: "",
//   右中指２: "",
//   右中指３: "",
//   "Distal Middle.R_end": "",
//   右小指１: "",
//   右小指２: "",
//   右小指３: "",
//   "Distal Little.R_end": "",
//   右人指１: "",
//   右人指２: "",
//   右人指３: "",
//   "Distal Index.R_end": "",
//   左肩: "",
//   左腕: "",
//   左ひじ: "",
//   左手首: "",
//   左親指０: "",
//   左親指１: "",
//   左親指２: "",
//   "Distal Thumb.L_end": "",
//   左薬指１: "",
//   左薬指２: "",
//   左薬指３: "",
//   "Distal Ring.L_end": "",
//   左中指１: "",
//   左中指２: "",
//   左中指３: "",
//   "Distal Middle.L_end": "",
//   左小指１: "",
//   左小指２: "",
//   左小指３: "",
//   "Distal Little.L_end": "",
//   左人指１: "",
//   左人指２: "",
//   左人指３: "",
//   "Distal Index.L_end": "",
//   首: "",
//   "Breast.R": "",
//   "Breast.R_end": "",
//   "Breast.L": "",
//   "Breast.L_end": "",
//   左足ＩＫ: "",
//   左つま先ＩＫ: "",
//   右足ＩＫ: "",
//   右つま先ＩＫ: "",
//   右腕捩: "",
//   左腕捩: "",
//   右手捩: "",
//   左手捩: "",
//   頭: "",
//   両目: "",
//   舌１: "",
//   舌２: "",
//   舌３: "",
//   涙左: "",
//   涙右: "",
//   鼻水: "",
//   めがね: "",
//   左目: "",
//   左目戻: "",
//   右目: "",
//   右目戻: "",
//   髪P: "",
//   "横髪1.L": "",
//   前髪2: "",
//   前髪3: "",
//   前髪1: "",
//   前髪4: "",
//   "横髪2.L": "",
//   前髪5: "",
//   "横髪2.R": "",
//   "横髪3.L": "",
//   "横髪3.R": "",
//   "横髪1.R": "",
//   "横髪4.L": "",
//   "横髪4.R": "",
//   後髪1: "",
//   "後髪2.L": "",
//   "後髪3.L": "",
//   "後髪4.L": "",
//   "後髪5.L": "",
//   "後髪6.L": "",
//   "後髪7.L": "",
//   "後髪2.R": "",
//   "後髪3.R": "",
//   "後髪4.R": "",
//   "後髪5.R": "",
//   "後髪6.R": "",
//   "後髪7.R": "",
//   左耳１: "",
//   左耳２: "",
//   右耳１: "",
//   右耳２: "",
// };

export const blendshape_map_by_MMD_name_VRM1 = {
  あ: "aa",
  あ２: "aa",

  い: "ih",

  う: "ou",
  //"ω"

  え: "ee",
  //"にやり"

  お: "oh",

  まばたき: "blink",

  まばたきL: "blinkLeft",
  ウィンク: "blinkLeft",
  ウィンク２: "blinkLeft",

  まばたきR: "blinkRight",
  ウィンク右: "blinkRight",
  ｳｨﾝｸ２右: "blinkRight",

  にこり: "relaxed",
  困る: "sad",
  怒り: "angry",
  笑い: "happy",
  //"びっくり": "Surprise",
};

export const blendshape_map_by_MMD_name_VRM0 = {
  あ: "a",
  あ２: "a",

  い: "i",

  う: "u",
  //"ω"

  え: "e",
  //"にやり"

  お: "o",

  まばたき: "blink",

  まばたきL: "blink_l",
  ウィンク: "blink_l",
  ウィンク２: "blink_l",

  まばたきR: "blink_r",
  ウィンク右: "blink_r",
  ｳｨﾝｸ２右: "blink_r",

  にこり: "fun",
  困る: "sorrow",
  怒り: "angry",
  笑い: "joy",
  //"びっくり": "Surprise",
};
